#!/usr/bin/env python3
"""Synchronize snow-sensor.timer interval from station config."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# Ensure local imports work when executed directly.
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.sensor.station_config import load_config, validate_config

TIMER_OVERRIDE_DIR = Path("/etc/systemd/system/snow-sensor.timer.d")
TIMER_OVERRIDE_PATH = TIMER_OVERRIDE_DIR / "override.conf"


def _render_override(interval_minutes: int) -> str:
    return (
        "# Auto-generated by scripts/sync_timer_interval.py\n"
        "[Timer]\n"
        f"OnUnitActiveSec={interval_minutes}min\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync snow-sensor.timer interval from config timing")
    parser.add_argument(
        "--config",
        default=str(REPO_ROOT / "config" / "station_01.yaml"),
        help="Path to station config YAML",
    )
    parser.add_argument(
        "--no-restart",
        action="store_true",
        help="Do not restart snow-sensor.timer after writing override",
    )
    args = parser.parse_args()

    try:
        cfg = load_config(args.config)
    except Exception as exc:
        print(f"[ERROR] Failed to load config: {exc}", file=sys.stderr)
        return 1

    errors = validate_config(cfg)
    if errors:
        print("[ERROR] Config validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 2

    interval_minutes = int(cfg.timing.cycle_interval_minutes)
    if interval_minutes < 1:
        print("[ERROR] timing.cycle_interval_minutes must be >= 1", file=sys.stderr)
        return 2

    try:
        TIMER_OVERRIDE_DIR.mkdir(parents=True, exist_ok=True)
        TIMER_OVERRIDE_PATH.write_text(_render_override(interval_minutes), encoding="utf-8")
        subprocess.run(["systemctl", "daemon-reload"], check=True)
        if not args.no_restart:
            subprocess.run(["systemctl", "restart", "snow-sensor.timer"], check=True)
    except Exception as exc:
        print(f"[ERROR] Failed to apply timer override: {exc}", file=sys.stderr)
        return 3

    print(
        "Updated snow-sensor.timer interval from config: "
        f"timing.cycle_interval_minutes={interval_minutes}"
    )
    print(f"Override file: {TIMER_OVERRIDE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
